### ISSUE TITLE
No BLE module found

### ISSUE THREAD

**Issue by amnagh017** [bardiabarabadi/uvicMUSE#16]
Having the same issue (https://github.com/bardiabarabadi/uvicMUSE/issues/7#issuecomment-744085039) in Windows 10.

I have checked Radios / Bluetooth access in privacy settings but still the same error.

Any suggestions?

**Comment by TenaciousC22** [comment]
Pinging this as I am having the same issue. I'm using the Sabrent BT-40 adapter recommended on the lab page. I have installed the drivers provided by the manufacturer and my laptop recognizes the device as a bluetooth radio. I disabled the onboard bluetooth radio and I still get this issue. 

Suggestions?

**Comment by alexandershaw4** [comment]
Same issue here

**Comment by akashkulgod-web** [comment]
did anyone find a solution?

**Comment by markedschroeder** [comment]
I'm having the same issue. The terminal has permission to access Bluetooth, which solved this issue in "uvicMuse not starting on Osx 11.0.1 #7", but is not fixing it for me.

When I use the python code in that issue, I get an error after the line "M_wrapper.search_and_connect()"

Python 3.8.16 (default, Mar  1 2023, 21:19:10) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from uvicmuse.MuseWrapper import MuseWrapper as MW
>>> import asyncio
>>> loop = asyncio.get_event_loop()
>>> M_wrapper = MW (loop = loop, target_name = None, timeout = 10, max_buff_len = 500)
>>> M_wrapper.search_and_connect() # returnes True if the connection is successful
/Users/marks/miniconda3/envs/muse_env3/lib/python3.8/site-packages/uvicmuse/MuseFinder.py:18: FutureWarning: The discover function will removed in a future version, use BleakScanner.discover instead.
  devices = await discover(timeout=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marks/miniconda3/envs/muse_env3/lib/python3.8/site-packages/uvicmuse/MuseWrapper.py", line 37, in search_and_connect
    loop.run_until_complete(mf.search_for_muses(timeout=self.timeout))
  File "/Users/marks/miniconda3/envs/muse_env3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/marks/miniconda3/envs/muse_env3/lib/python3.8/site-packages/uvicmuse/MuseFinder.py", line 20, in search_for_muses
    if MUSE_NAME in d.name and not self._is_already_found(newly_found_muse=d):
TypeError: argument of type 'NoneType' is not iterable

I also installed Scipy since I started with miniconda. The only error I got during install was that it installed cryptography 40.0.2 and pyopenssl 23.0.0 requires a version <40, >=38.0.0. I get the same BLE error with either 40.0.2 and 39.0.2.

Thanks for any help you can provide!

**Comment by dwebster300** [comment]
I got this from ChatGPT... and will try it out this weekend.
But posting in case any of these suggestions help anyone else... regardless if I'm successful or not.

The message "no BLE module found" usually indicates that your computer is either not recognizing the Bluetooth Low Energy (BLE) module, or it's not properly installed or functioning. Here are some steps you can take to troubleshoot the issue:

1. **Check your Device Manager:** The Device Manager in Windows allows you to see and manage the hardware attached to your computer. To access it, you need to:
   - Press the Windows Key + X and select Device Manager from the list.
   - Look for "Bluetooth" in the list of device categories. If you see a yellow exclamation mark, a question mark, or the Bluetooth category is not present, there may be an issue with your Bluetooth hardware or driver.

2. **Check your Bluetooth Driver:**
   - If you found an issue with the Bluetooth category in Device Manager, you should try updating or reinstalling the Bluetooth driver. 
   - To update, right-click on the Bluetooth device in the Device Manager and select "Update Driver". Choose the automatic search option to allow Windows to look for the best driver.
   - To reinstall, right-click the Bluetooth device, choose "Uninstall device", then restart your computer. Windows should automatically reinstall the driver on startup.
   - If automatic update or reinstall doesn't work, visit Sabrent's official website and download the latest drivers for your specific model. Install the drivers manually by using the 'Browse my computer for drivers' option in Device Manager.

3. **Make sure Bluetooth is Enabled:**
   - Sometimes, the issue is as simple as having Bluetooth disabled. You can enable Bluetooth by going to Settings > Devices > Bluetooth & other devices. Make sure the toggle for Bluetooth is switched to "On".

4. **Check the Bluetooth Support Service:**
   - Windows runs a service in the background to manage Bluetooth functionality. Make sure this service is running:
   - Press the Windows key + R to open the Run dialog box.
   - Type in "services.msc" and press Enter.
   - Scroll down to find "Bluetooth Support Service". 
   - If the service isn't running, right-click on it and click "Start". If it's already running, try restarting it. To do this, right-click the service and choose "Restart".
   - Also, ensure that the startup type is set to "Automatic".

5. **Run Windows Troubleshooter:**
   - Windows includes a built-in tool to help troubleshoot and fix issues with various components of your system, including Bluetooth.
   - Go to Settings > Update & Security > Troubleshoot. 
   - Find "Bluetooth" and click "Run the troubleshooter". Follow the prompts and let Windows find and fix any problems.

If none of these steps work, your Sabrent Bluetooth module may be faulty or incompatible with your system. You may need to contact Sabrent's customer support or consider getting a replacement module.
