### ISSUE TITLE
x86_64 need arm64 liblsl64.dylib

### ISSUE THREAD

**Issue by andraderenew** [bardiabarabadi/uvicMUSE#20]
Dear community,

I have had some issues with kivy. I can't get kivy 2.0.0rc4 installed. It only instals 2.2.1. Now I have this. 

Thanks for all the help in advance. 

[INFO   ] [Logger      ] Record log in /Users/andraderenew/.kivy/logs/kivy_23-12-17_26.txt
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ]
[INFO   ] [Python      ] Interpreter at "/Users/andraderenew/anaconda3/envs/muse_env/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Metal - 88'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple M1'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x12a98c740>" has been set, it will be removed in a future version
[WARNING] Deprecated property "<BooleanProperty name=keep_ratio>" of object "<kivy.uix.image.Image object at 0x12a98c740>" was accessed, it will be removed in a future version
 Traceback (most recent call last):
   File "/Users/andraderenew/anaconda3/envs/muse_env/bin/uvicmuse", line 8, in <module>
     sys.exit(main())
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/uvicmuse/__main__.py", line 7, in main
     runGUI()
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/uvicmuse/interface.py", line 343, in runGUI
     loop.run_until_complete(App.async_run(MuseApp(), async_lib='asyncio'))
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/nest_asyncio.py", line 99, in run_until_complete
     return f.result()
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/asyncio/futures.py", line 178, in result
     raise self._exception
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/asyncio/tasks.py", line 280, in __step
     result = coro.send(None)
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/kivy/app.py", line 967, in async_run
     self._run_prepare()
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/uvicmuse/interface.py", line 338, in build
     return UVicMuse()
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/uvicmuse/interface.py", line 156, in __init__
     from uvicmuse.Backend import Backend
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/uvicmuse/Backend.py", line 14, in <module>
     from pylsl import StreamInfo, StreamOutlet
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/__init__.py", line 2, in <module>
     from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/pylsl.py", line 1147, in <module>
     lib = CDLL(libpath)
   File "/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/ctypes/__init__.py", line 373, in __init__
     self._handle = _dlopen(self._name, mode)
 OSError: dlopen(/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/liblsl64.dylib, 0x0006): tried: '/Applications/freesurfer/7.3.2/lib/gcc/lib/liblsl64.dylib' (no such file), '/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/liblsl64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/liblsl64.dylib' (no such file), '/Users/andraderenew/anaconda3/envs/muse_env/lib/python3.8/site-packages/pylsl/liblsl64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by andraderenew** [comment]
I have installed kivy with this. 

# Install missing tools and libraries
brew install pkg-config sdl2 sdl2_ttf sdl2_image sdl2_mixer gstreamer

# Upgrade pip, setuptools, wheel, and cython
pip install --upgrade pip setuptools wheel cython

# Clean up previous kivy build artifacts if any
pip uninstall kivy

# Install kivy
pip install kivy


But the problem is when installing uvicmuse 5.3.3. 


      
      
      Found Cython at /private/var/folders/hw/6wwzz1z53vndr74qc1hc01wc0000gn/T/pip-build-env-htuvm52p/overlay/lib/python3.8/site-packages/Cython/__init__.py
      Detected supported Cython version 0.29.21
      User distribution detected, avoid portable command.
      Using this graphics system: OpenGL ES 2
      OSX framework used, force to x86_64 only
      OSX ARCHFLAGS are: -arch x86_64
      GStreamer framework not found, fallback on pkg-config
      GStreamer found via pkg-config
      Missing framework /Library/Frameworks/SDL2.framework
      Missing framework /Library/Frameworks/SDL2_ttf.framework
      Missing framework /Library/Frameworks/SDL2_image.framework
      Missing framework /Library/Frameworks/SDL2_mixer.framework
      SDL2 frameworks not found, fallback on pkg-config
      SDL2 found via pkg-config
      Xcode detected at b'/Library/Developer/CommandLineTools', and using OS X14.5 sdk
      Pango: pangoft2 found via pkg-config
      {'libraries': ['pangoft2-1.0', 'pango-1.0', 'gobject-2.0', 'glib-2.0', 'intl', 'harfbuzz', 'fontconfig', 'freetype'], 'include_dirs': ['/private/var/folders/hw/6wwzz1z53vndr74qc1hc01wc0000gn/T/pip-install-_s6wa1of/kivy_1e0e5b8d0e404d12926e7502a9705fa5/kivy/include', '/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0', '/opt/homebrew/Cellar/harfbuzz/8.5.0/include/harfbuzz', '/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0', '/opt/homebrew/Cellar/glib/2.80.3/include', '/opt/homebrew/Cellar/fribidi/1.0.15/include/fribidi', '/opt/homebrew/Cellar/cairo/1.18.0/include/cairo', '/opt/homebrew/Cellar/libxext/1.3.6/include', '/opt/homebrew/Cellar/libxrender/0.9.11/include', '/opt/homebrew/Cellar/libx11/1.8.9/include', '/opt/homebrew/Cellar/libxcb/1.17.0/include', '/opt/homebrew/Cellar/libxau/1.0.11/include', '/opt/homebrew/Cellar/libxdmcp/1.1.5/include', '/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1', '/opt/homebrew/Cellar/glib/2.80.3/include', '/opt/homebrew/Cellar/harfbuzz/8.5.0/include/harfbuzz', '/opt/homebrew/Cellar/glib/2.80.3/include/glib-2.0', '/opt/homebrew/Cellar/glib/2.80.3/lib/glib-2.0/include', '/opt/homebrew/opt/gettext/include', '/opt/homebrew/Cellar/pcre2/10.44/include', '/opt/homebrew/Cellar/graphite2/1.3.14/include', '/opt/homebrew/Cellar/fontconfig/2.15.0/include', '/opt/homebrew/opt/freetype/include/freetype2', '/opt/homebrew/opt/libpng/include/libpng16', '/opt/homebrew/Cellar/xorgproto/2024.1/include', '/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi'], 'library_dirs': ['/opt/homebrew/Cellar/pango/1.54.0/lib', '/opt/homebrew/Cellar/glib/2.80.3/lib', '/opt/homebrew/opt/gettext/lib', '/opt/homebrew/Cellar/harfbuzz/8.5.0/lib', '/opt/homebrew/Cellar/fontconfig/2.15.0/lib', '/opt/homebrew/opt/freetype/lib'], 'extra_link_args': ['-F/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks'], 'extra_compile_args': ['-F/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks'], 'depends': ['lib/pango/pangoft2.pxi', 'lib/pango/pangoft2.h']}
      ERROR: Dependency for context.pyx not resolved: config.pxi
      ERROR: Dependency for compiler.pyx not resolved: config.pxi
      ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for fbo.pyx not resolved: config.pxi
      ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for instructions.pyx not resolved: config.pxi
      ERROR: Dependency for opengl.pyx not resolved: config.pxi
      ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
      ERROR: Dependency for shader.pyx not resolved: config.pxi
      ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for texture.pyx not resolved: config.pxi
      ERROR: Dependency for vbo.pyx not resolved: config.pxi
      ERROR: Dependency for vertex.pyx not resolved: config.pxi
      ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for cgl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
      ERROR: Dependency for svg.pyx not resolved: config.pxi
      Building extensions in parallel using 4 cores
      Updated build directory to: build/lib.macosx-11.1-arm64-cpython-38
      Build configuration is:
       * use_rpi = 0
       * use_egl = 0
       * use_opengl_es2 = 1
       * use_opengl_mock = 0
       * use_sdl2 = 1
       * use_pangoft2 = 1
       * use_ios = 0
       * use_android = 0
       * use_mesagl = 0
       * use_x11 = 0
       * use_wayland = 0
       * use_gstreamer = 1
       * use_avfoundation = 1
       * use_osx_frameworks = 1
       * debug_gl = 0
       * kivy_sdl_gl_alpha_size = 8
       * debug = False
      Updated build/lib.macosx-11.1-arm64-cpython-38/kivy/include/config.h
      Updated /private/var/folders/hw/6wwzz1z53vndr74qc1hc01wc0000gn/T/pip-install-_s6wa1of/kivy_1e0e5b8d0e404d12926e7502a9705fa5/kivy/include/config.h
      Updated build/lib.macosx-11.1-arm64-cpython-38/kivy/include/config.pxi
      Updated /private/var/folders/hw/6wwzz1z53vndr74qc1hc01wc0000gn/T/pip-install-_s6wa1of/kivy_1e0e5b8d0e404d12926e7502a9705fa5/kivy/include/config.pxi
      Updated build/lib.macosx-11.1-arm64-cpython-38/kivy/setupconfig.py
      Updated /private/var/folders/hw/6wwzz1z53vndr74qc1hc01wc0000gn/T/pip-install-_s6wa1of/kivy_1e0e5b8d0e404d12926e7502a9705fa5/kivy/setupconfig.py
      Detected compiler is unix
       <string>:374: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:377: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:381: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       warning: kivy/graphics/common.pxi:9:4: 'const_char_ptr' redeclared
       warning: kivy/graphics/common.pxi:23:4: 'size_t' redeclared
       error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kivy
Failed to build kivy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (kivy)

**Comment by andraderenew** [comment]
I could finally make linux version 3.3.3 work in mac os sonoma 14.5 chip M1. So it's a matter of installing pylsl with conda and that's it.

**Comment by kevinychou** [comment]
Hey @andraderenew - I'm having the same issue installing uvicmuse 5.3.3. Any advice on how you got the version working?
I'm also on Mac OS chip M2, Sonoma 14.5.

**Comment by andraderenew** [comment]
> Hey @andraderenew - I'm having the same issue installing uvicmuse 5.3.3. Any advice on how you got the version working? I'm also on Mac OS chip M2, Sonoma 14.5.

Basically with Linux version!!

**Comment by kevinychou** [comment]
Thanks, this worked!
